project('anem16sim', 'cpp',
  version : '1.0',
  default_options : ['cpp_std=c++20', 'warning_level=2'])

sources = [
  'alu.cpp',
  'cpu.cpp',
  'debug.cpp',
  'disasm.cpp',
  'except.cpp',
  'instrset.cpp',
  'main.cpp',
  'mem.cpp',
  'regbnk.cpp',
  'periph/mac.cpp',
  'stats/stats.cpp',
]

executable('sim', sources)
